package handler

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"country-search-api/internal/models"
	
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockCountryService is an autogenerated mock type for the CountryService type
type MockCountryService struct {
	mock.Mock
}

// SearchCountry provides a mock function with given fields: ctx, name
func (_m *MockCountryService) SearchCountry(ctx context.Context, name string) (*models.Country, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.Country
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Country); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Country)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestSearch_Success(t *testing.T) {
	mockSvc := new(MockCountryService)
	h := NewCountryHandler(mockSvc)

	expectedCountry := &models.Country{
		Name:       "India",
		Capital:    "New Delhi",
		Currency:   "₹",
		Population: 1380000000,
	}

	mockSvc.On("SearchCountry", mock.Anything, "India").Return(expectedCountry, nil)

	req := httptest.NewRequest(http.MethodGet, "/api/countries/search?name=India", nil)
	w := httptest.NewRecorder()

	h.Search(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Contains(t, w.Body.String(), `"name":"India"`)
	assert.Contains(t, w.Body.String(), `"capital":"New Delhi"`)
}

func TestSearch_MissingNameParameter(t *testing.T) {
	mockSvc := new(MockCountryService)
	h := NewCountryHandler(mockSvc)

	req := httptest.NewRequest(http.MethodGet, "/api/countries/search", nil)
	w := httptest.NewRecorder()

	h.Search(w, req)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.Contains(t, w.Body.String(), "Query parameter 'name' is required")
}

func TestSearch_MethodNotAllowed(t *testing.T) {
	mockSvc := new(MockCountryService)
	h := NewCountryHandler(mockSvc)

	req := httptest.NewRequest(http.MethodPost, "/api/countries/search?name=India", nil)
	w := httptest.NewRecorder()

	h.Search(w, req)

	assert.Equal(t, http.StatusMethodNotAllowed, w.Code)
}

func TestSearch_ServiceError(t *testing.T) {
	mockSvc := new(MockCountryService)
	h := NewCountryHandler(mockSvc)

	mockSvc.On("SearchCountry", mock.Anything, "Unknown").Return(nil, errors.New("country not found"))

	req := httptest.NewRequest(http.MethodGet, "/api/countries/search?name=Unknown", nil)
	w := httptest.NewRecorder()

	h.Search(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code)
}
