package client

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

// Do provides a mock function with given fields: req
func (_m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestFetchCountry_Success(t *testing.T) {
	mockClient := new(MockHTTPClient)
	c := NewRESTCountriesClient(mockClient)

	// Mocking successful response
	jsonResponse := `[{"name":{"common":"India"},"capital":["New Delhi"],"currencies":{"INR":{"name":"Indian rupee","symbol":"₹"}},"population":1380004385}]`
	respBody := io.NopCloser(bytes.NewBufferString(jsonResponse))
	
	mockClient.On("Do", mock.Anything).Return(&http.Response{
		StatusCode: http.StatusOK,
		Body:       respBody,
	}, nil)

	ctx := context.Background()
	country, err := c.FetchCountry(ctx, "India")

	assert.NoError(t, err)
	assert.NotNil(t, country)
	assert.Equal(t, "India", country.Name)
	assert.Equal(t, "New Delhi", country.Capital)
	assert.Equal(t, "₹", country.Currency)
	assert.Equal(t, 1380004385, country.Population)

	mockClient.AssertExpectations(t)
}

func TestFetchCountry_NotFound(t *testing.T) {
	mockClient := new(MockHTTPClient)
	c := NewRESTCountriesClient(mockClient)

	respBody := io.NopCloser(bytes.NewBufferString(`{"status": 404, "message": "Not Found"}`))
	mockClient.On("Do", mock.Anything).Return(&http.Response{
		StatusCode: http.StatusNotFound,
		Body:       respBody,
	}, nil)

	ctx := context.Background()
	country, err := c.FetchCountry(ctx, "Unknown")

	assert.Error(t, err)
	assert.Nil(t, country)
	assert.Equal(t, "country not found", err.Error())

	mockClient.AssertExpectations(t)
}

func TestFetchCountry_RequestError(t *testing.T) {
	mockClient := new(MockHTTPClient)
	c := NewRESTCountriesClient(mockClient)

	mockClient.On("Do", mock.Anything).Return(nil, errors.New("network error"))

	ctx := context.Background()
	country, err := c.FetchCountry(ctx, "India")

	assert.Error(t, err)
	assert.Nil(t, country)
	assert.Contains(t, err.Error(), "failed to execute request")

	mockClient.AssertExpectations(t)
}

func TestFetchCountry_Timeout(t *testing.T) {
	mockClient := new(MockHTTPClient)
	c := NewRESTCountriesClient(mockClient)

	// Context with timeout to verify the behavior
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond)
	cancel() // instantly cancel to simulate timeout

	mockClient.On("Do", mock.Anything).Return(nil, context.Canceled)

	country, err := c.FetchCountry(ctx, "India")

	assert.Error(t, err)
	assert.Nil(t, country)
	assert.Contains(t, err.Error(), "failed to execute request")

	mockClient.AssertExpectations(t)
}
