package service

import (
	"context"
	"errors"
	"testing"

	"country-search-api/internal/cache"
	"country-search-api/internal/models"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// FetchCountry provides a mock function with given fields: ctx, name
func (_m *MockClient) FetchCountry(ctx context.Context, name string) (*models.Country, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.Country
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Country); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Country)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestSearchCountry_CacheHit(t *testing.T) {
	mockCache := cache.NewMemoryCache()
	mockClient := new(MockClient)

	svc := NewCountryService(mockCache, mockClient)

	expectedCountry := &models.Country{
		Name:       "India",
		Capital:    "New Delhi",
		Currency:   "₹",
		Population: 1380000000,
	}

	// Preset cache
	mockCache.Set("india", expectedCountry)

	// We don't expect the client to be called
	// mockClient.On("FetchCountry", mock.Anything, mock.Anything).Return(nil, nil)

	ctx := context.Background()
	country, err := svc.SearchCountry(ctx, "India")

	assert.NoError(t, err)
	assert.Equal(t, expectedCountry, country)

	mockClient.AssertNotCalled(t, "FetchCountry")
}

func TestSearchCountry_CacheMiss_Success(t *testing.T) {
	mockCache := cache.NewMemoryCache()
	mockClient := new(MockClient)

	svc := NewCountryService(mockCache, mockClient)

	expectedCountry := &models.Country{
		Name:       "India",
		Capital:    "New Delhi",
		Currency:   "₹",
		Population: 1380000000,
	}

	mockClient.On("FetchCountry", mock.Anything, "India").Return(expectedCountry, nil)

	ctx := context.Background()
	// First call - Cache Miss
	country, err := svc.SearchCountry(ctx, "India")

	assert.NoError(t, err)
	assert.Equal(t, expectedCountry, country)
	mockClient.AssertExpectations(t)

	// Verify it was stored in cache
	cachedVal, exists := mockCache.Get("india")
	assert.True(t, exists)
	assert.Equal(t, expectedCountry, cachedVal)
	
	// Ensure client was only called once
	mockClient.AssertNumberOfCalls(t, "FetchCountry", 1)
}

func TestSearchCountry_ClientError(t *testing.T) {
	mockCache := cache.NewMemoryCache()
	mockClient := new(MockClient)

	svc := NewCountryService(mockCache, mockClient)

	mockClient.On("FetchCountry", mock.Anything, "Unknown").Return(nil, errors.New("country not found"))

	ctx := context.Background()
	country, err := svc.SearchCountry(ctx, "Unknown")

	assert.Error(t, err)
	assert.Nil(t, country)
	assert.Contains(t, err.Error(), "service failed to fetch country")

	// Ensure cache miss doesn't store anything
	_, exists := mockCache.Get("unknown")
	assert.False(t, exists)
}
